name: landscape_clock
description: Landscape clock.
version: 1.0.0+1

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_clock_helper:
    path: ../flutter_clock_helper
  cupertino_icons: ^0.1.2
#  google_fonts: ^0.2.0
  tinycolor: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/landscape1/landscape.png
    - assets/sun.png
    - assets/moon.png
    - assets/weather/cloudy.png
    - assets/weather/rainy.png
    - assets/weather/snowy.png
    - assets/weather/sunny.png
  fonts:
    - family: ChangaOne-Regular
      fonts:
        - asset: third_party/ChangaOne-Regular.ttf
